namespace SpaceAdventure.Shared.Model;

// M74 (humble-soaring-cat.md) - unified, ECS-style aggregation over every physical device fixture
// Ship already tracks via its own separate typed fields (ReactorBlock, Turrets, Cameras, SystemDevices,
// ...). Purely an ADDITIVE read-only VIEW, the same "generate both representations from one source of
// truth" strategy TileGridRasterizer (M71) already used for Rooms/Doors/WallBlocks -> TileGrid:
// nothing about the old fields changes or goes away, Ship.Devices (Ship.cs) is just a flattened
// projection over them, built once in the Ship constructor. No wiring/PowerSystemId/footprint fields -
// every device here is exactly one interactable point (Kind + RoomId + position), per the plan's own
// decision that devices stay 1x1 and wiring-free through M74.
//
// PowerSystemId.Secondary has no DeviceKind counterpart (user's explicit decision - "вид устройства
// Secondary в новую модель НЕ переносится вообще") - a ship's own "system-secondary" ShipSystemDevice
// (still fully present on Ship.SystemDevices, untouched) is simply skipped when building this list.
// DeviceKind.Junction has no producer yet - nothing places a physical Junction device on Ship today
// (the "Кор" box the player sees is still auto-generated by WireGraphFactory, never stored here) -
// the value exists so a future placement tool (M76) has somewhere to put one; same story for
// Distribution, which DOES have a live fixture (PowerDistributionBlock) but, like Junction, carries
// no function of its own yet (wiring is out of scope through M74 - see the plan's own decisions).
public enum DeviceKind
{
    Reactor, Distribution, Battery, Helm, Navigation, CardTable, Jukebox,
    Engine, Shields, WeaponCharger, Oxygen,
    TurretBallistic, TurretLaser, TurretMachineGun,
    AmmoStorage, SuitLocker, StorageRack, Camera, ComponentMount, Junction,
}

public sealed record ShipDevice(
    string Id, DeviceKind Kind, string RoomId, float X, float Y,
    TurretMountSide MountSide = TurretMountSide.Aft,
    CameraMountSide? CameraSide = null,
    string? TargetDoorId = null,
    float ThrustBonus = 0f, float TurnBonus = 0f, float CapacityBonus = 0f)
{
    public Vec2 Position => new(X, Y);
}
