using System;
using System.Collections.Generic;
using System.Linq;
using SpaceAdventure.Shared.Model;

namespace SpaceAdventure.Client;

// Bridges the free-form tile canvas (_editorTiles, a real TileGrid) into the Room-rectangle-based
// CustomShipDefinition the rest of the game (Ship.FromCustomDefinition, CustomShipValidator, Save/
// Load/Play) already understands - direct user request ("добавь возможность поиграть на построенном
// корабле"). The two models disagree on one structural point: a wall/door tile in the free-form
// canvas occupies a WHOLE separate tile (its own floor slot), while a Room-rectangle's walls are
// zero-thickness lines exactly on its boundary - two Room rectangles that are meant to be adjacent
// must touch exactly, with no gap, for Ship.FromCustomDefinition's own wall/door generation
// (ShipLayoutGeometry.FindRoomPairOverlaps) to find them at all. A region's own open-floor bounding
// box, taken as-is, would leave a real 1-tile gap wherever the player painted a connecting wall/door,
// so BuildDefinitionFromTiles closes that gap by extending one side's rectangle by exactly 1 tile
// onto the separating wall/door column/row - which is also exactly where Ship.FromCustomDefinition's
// own auto-generated interior wall ends up landing (GenerateInteriorWallBlocks in Ship.cs). The
// player's own painted wall/door tile becomes reference art for shaping the rooms, not a rendered
// object in its own right, once converted - the actual in-game walls/doors are freshly generated by
// the existing Room/Door pipeline, unchanged.
public partial class Game1
{
    // Every call site (the bottom-bar status line, the Play button) wants both "can this even be
    // turned into rooms at all" (rectangularity - a genuine tile-model concept with no equivalent in
    // CustomShipValidator) and the existing validator's own rules (device minimums, airlocks, ...)
    // in one combined pass, so there's a single source of truth for "is Play enabled right now."
    private (CustomShipDefinition Definition, IReadOnlyList<string> Errors) BuildAndValidateEditorDefinition()
    {
        var (definition, tileErrors) = BuildDefinitionFromTiles();
        var named = (definition ?? CustomShipDefinition.Empty) with { Name = _editorShipName, ForwardDegrees = _editorForwardDegrees };
        if (tileErrors.Count > 0)
            return (named, tileErrors);
        return (named, CustomShipValidator.Validate(named));
    }

    // Delegates the actual TileGrid -> CustomShipDefinition conversion to TileShipBuilder (Shared) -
    // the exact same algorithm this method used to implement by hand, ported so a compartment-
    // catalog-built hull (Ship.cs's Destroyer/Freighter) can reuse it too. This method now only
    // adapts this class's own editor fields into that method's plain-parameter shape: engines get
    // the editor's single flat EngineMaxThrust constant (the free-tile Engine tool has no notion of
    // per-size thrust), zones carry over as-is for the friendly-room-naming feature.
    private (CustomShipDefinition? Definition, IReadOnlyList<string> Errors) BuildDefinitionFromTiles()
    {
        var engines = _editorEngineFacing.ToDictionary(kv => kv.Key, kv => new TileShipBuilder.EngineSpec(kv.Value, EngineMaxThrust));
        var zones = _editorZones.Select(z => (z.Name, (IReadOnlySet<TileCoord>)z.Tiles)).ToList();
        return TileShipBuilder.BuildDefinition(_editorTiles, _editorDeviceKinds, engines, _editorShipName, _editorForwardDegrees, zones);
    }
}
