using SpaceAdventure.Server;
using SpaceAdventure.Shared.Model;
using SpaceAdventure.Shared.Networking;
using SpaceAdventure.Shared.Protocol;

internal static partial class TestRunner
{
    private static readonly (string Name, Func<bool> Run)[] Tests =
    {
        ("Smoke_ProjectsWireUpCorrectly", Smoke_ProjectsWireUpCorrectly),
        ("InProcessTransport_DeliversCommandToServer", InProcessTransport_DeliversCommandToServer),
        ("GameServer_TickIncrementsAndBroadcastsSnapshot", GameServer_TickIncrementsAndBroadcastsSnapshot),
        ("World_Step_MovesCharacterTowardInput", World_Step_MovesCharacterTowardInput),
        ("World_Step_ClampsToShipBounds", World_Step_ClampsToShipBounds),
        ("GameServer_Tick_AppliesMoveCommandFromClient", GameServer_Tick_AppliesMoveCommandFromClient),
        ("Ship_MoveAlongAxis_BlocksAtWallWithoutDoor", Ship_MoveAlongAxis_BlocksAtWallWithoutDoor),
        ("Ship_MoveAlongAxis_PassesThroughAlignedDoor", Ship_MoveAlongAxis_PassesThroughAlignedDoor),
        ("Ship_MoveAlongAxis_BlockedWhenMisalignedWithDoor", Ship_MoveAlongAxis_BlockedWhenMisalignedWithDoor),
        ("Reactor_Step_DepletesFuelProportionalToUsage", Reactor_Step_DepletesFuelProportionalToUsage),
        ("Reactor_CurrentOutput_DropsToZeroWhenFuelDepleted", Reactor_CurrentOutput_DropsToZeroWhenFuelDepleted),
        ("World_NewCampaign_StartsWithAnEqualShareForEverySystem", World_NewCampaign_StartsWithAnEqualShareForEverySystem),
        ("World_TutorialWorld_StartsWithNothingAllocated", World_TutorialWorld_StartsWithNothingAllocated),
        ("PowerGrid_Allocation_CannotExceedReactorOutput", PowerGrid_Allocation_CannotExceedReactorOutput),
        ("PowerGrid_TwoPlayers_CanAdjustDifferentSlidersSimultaneously", PowerGrid_TwoPlayers_CanAdjustDifferentSlidersSimultaneously),
        ("PowerGrid_Battery_ChargesFromSurplus", PowerGrid_Battery_ChargesFromSurplus),
        ("PowerGrid_Battery_DischargesToCoverReactorShortfall", PowerGrid_Battery_DischargesToCoverReactorShortfall),
        ("World_ToggleManning_RequiresProximityToPeriscope", World_ToggleManning_RequiresProximityToPeriscope),
        ("World_ToggleManning_SucceedsNearPeriscope", World_ToggleManning_SucceedsNearPeriscope),
        ("World_TurretAim_ClampsToDefinitionLimits", World_TurretAim_ClampsToDefinitionLimits),
        ("World_Fire_DamagesEnemyAndRespectsCooldown", World_Fire_DamagesEnemyAndRespectsCooldown),
        ("World_Battle_SquadronSpawnsInFieldAndClosesOnTheShip", World_Battle_SquadronSpawnsInFieldAndClosesOnTheShip),
        ("World_Battle_EnemyFire_IsBlockedByAnAsteroid", World_Battle_EnemyFire_IsBlockedByAnAsteroid),
        ("World_Battle_FlyingClearOfTheSectorFleesTheFightWithoutAWin", World_Battle_FlyingClearOfTheSectorFleesTheFightWithoutAWin),
        ("World_Battle_ShipsDoNotOverlapWhenTheyCollide", World_Battle_ShipsDoNotOverlapWhenTheyCollide),
        ("World_Fire_ShellMissesWhenTheGunIsPointedAway", World_Fire_ShellMissesWhenTheGunIsPointedAway),
        ("World_Movement_LockedWhileManningTurret", World_Movement_LockedWhileManningTurret),
        ("World_Fire_EmptiesMagazineThenRefusesWithoutDamage", World_Fire_EmptiesMagazineThenRefusesWithoutDamage),
        ("World_PickUpAmmoCrate_RequiresProximityToStorage", World_PickUpAmmoCrate_RequiresProximityToStorage),
        ("World_PickUpAmmoCrate_SucceedsNearStorage", World_PickUpAmmoCrate_SucceedsNearStorage),
        ("World_ReloadTurret_RefillsAmmoAndClearsCarrying", World_ReloadTurret_RefillsAmmoAndClearsCarrying),
        ("EnemyShip_IsRetreating_BelowThreshold", EnemyShip_IsRetreating_BelowThreshold),
        ("EnemyShip_IsRetreating_FalseAboveThreshold", EnemyShip_IsRetreating_FalseAboveThreshold),
        ("World_EnemyAi_PriorityTargetingDisablesEnginesAndWeapons", World_EnemyAi_PriorityTargetingDisablesEnginesAndWeapons),
        ("World_Decompression_DrainsHealthInBreachedRoom", World_Decompression_DrainsHealthInBreachedRoom),
        ("World_Oxygen_GeneratorRestoresRoomOxygenWhenPowered", World_Oxygen_GeneratorRestoresRoomOxygenWhenPowered),
        ("World_RepairBreach_ClearsItViaInteract", World_RepairBreach_ClearsItViaInteract),
        ("World_Voyage_TravelingToHostileSectorStartsBattle", World_Voyage_TravelingToHostileSectorStartsBattle),
        ("World_Voyage_DefeatingEnemyReturnsToTraveling", World_Voyage_DefeatingEnemyReturnsToTraveling),
        ("World_Voyage_StationRefuelsAndClearsBreaches", World_Voyage_StationRefuelsAndClearsBreaches),
        ("World_Voyage_FlyingAwayFromTheBerthAbortsTheApproach", World_Voyage_FlyingAwayFromTheBerthAbortsTheApproach),
        ("World_EnemyAi_DormantWhileTraveling", World_EnemyAi_DormantWhileTraveling),
        ("World_SuitAction_RequiresProximityToLocker", World_SuitAction_RequiresProximityToLocker),
        ("World_SuitAction_TakesTimeAndLocksMovement", World_SuitAction_TakesTimeAndLocksMovement),
        ("World_SuitedCharacter_ImmuneToDecompression", World_SuitedCharacter_ImmuneToDecompression),
        ("World_SuitAction_IgnoredWhileMidAction", World_SuitAction_IgnoredWhileMidAction),
        ("World_Character_FacingTracksLastMoveDirection", World_Character_FacingTracksLastMoveDirection),
        ("World_LaserTurret_FiresUsingChargeWithoutAmmoCrate", World_LaserTurret_FiresUsingChargeWithoutAmmoCrate),
        ("World_LaserTurret_RechargesOnlyFromWeaponChargerAllocation", World_LaserTurret_RechargesOnlyFromWeaponChargerAllocation),
        ("World_Inventory_PickUpAmmoCrate_OccupiesMainSlot", World_Inventory_PickUpAmmoCrate_OccupiesMainSlot),
        ("World_Inventory_ReloadTurret_ClearsAmmoCrateFromSlot", World_Inventory_ReloadTurret_ClearsAmmoCrateFromSlot),
        ("World_Inventory_DonningSuit_OccupiesClothingSlot", World_Inventory_DonningSuit_OccupiesClothingSlot),
        ("Inventory_ToggleHold_OneHandedItemsShareBothHands", Inventory_ToggleHold_OneHandedItemsShareBothHands),
        ("Inventory_ToggleHold_TwoHandedItemDropsExistingHeldItem", Inventory_ToggleHold_TwoHandedItemDropsExistingHeldItem),
        ("Inventory_ToggleHold_ClickingHeldSlotAgainUnholds", Inventory_ToggleHold_ClickingHeldSlotAgainUnholds),
        ("World_TakeToolFromRack_AddsItToInventory", World_TakeToolFromRack_AddsItToInventory),
        ("World_WeldBreach_DoesNothingWithoutToolHeld", World_WeldBreach_DoesNothingWithoutToolHeld),
        ("World_SystemDamage_ZerosEffectiveAllocation", World_SystemDamage_ZerosEffectiveAllocation),
        ("World_RepairSystem_RequiresWrenchHeldInHand", World_RepairSystem_RequiresWrenchHeldInHand),
        ("World_RepairSystem_SinglePressDoesNotInstantlyFixIt", World_RepairSystem_SinglePressDoesNotInstantlyFixIt),
        ("Reactor_RemovingAllRods_ZerosOutput", Reactor_RemovingAllRods_ZerosOutput),
        ("Reactor_FreshRodIntoSpentSlot_ComesFullyCharged", Reactor_FreshRodIntoSpentSlot_ComesFullyCharged),
        ("Reactor_Step_BurnsRodsOneAtATime", Reactor_Step_BurnsRodsOneAtATime),
        ("World_ReactorSlot_InsertingCarriedRod_RefuelsFromEmpty", World_ReactorSlot_InsertingCarriedRod_RefuelsFromEmpty),
        ("World_ReactorSlot_RequiresProximityToReactor", World_ReactorSlot_RequiresProximityToReactor),
        ("World_ReactorSlot_RemoveRodReturnsItToInventory", World_ReactorSlot_RemoveRodReturnsItToInventory),
        ("World_ReactorSlot_InsertRequiresHoldingRod", World_ReactorSlot_InsertRequiresHoldingRod),
        ("World_ReactorSlot_ReinsertHeldRod", World_ReactorSlot_ReinsertHeldRod),
        ("Shield_TryAbsorbHit_DepletesPointsUntilEmpty", Shield_TryAbsorbHit_DepletesPointsUntilEmpty),
        ("World_Shield_AbsorbsFirstAttackWithoutDamagingShip", World_Shield_AbsorbsFirstAttackWithoutDamagingShip),
        ("World_Voyage_ShipMovesContinuouslyTowardTarget", World_Voyage_ShipMovesContinuouslyTowardTarget),
        ("World_Voyage_CannotChangeDestinationMidBattle", World_Voyage_CannotChangeDestinationMidBattle),
        ("World_Voyage_FreeFormClickFliesShipTowardArbitraryPoint", World_Voyage_FreeFormClickFliesShipTowardArbitraryPoint),
        ("World_Voyage_FreeFormClickNearHostileSectorStillTriggersBattle", World_Voyage_FreeFormClickNearHostileSectorStillTriggersBattle),
        ("World_Trade_BuyItem_DeductsCreditsAndAddsToInventory", World_Trade_BuyItem_DeductsCreditsAndAddsToInventory),
        ("World_Trade_BuyOxygenAndWeldingTank_AddsFullyChargedTanks", World_Trade_BuyOxygenAndWeldingTank_AddsFullyChargedTanks),
        ("World_Trade_BuyItem_FailsWithoutEnoughCredits", World_Trade_BuyItem_FailsWithoutEnoughCredits),
        ("World_Trade_BuyItem_FailsWhenInventoryFull", World_Trade_BuyItem_FailsWhenInventoryFull),
        ("World_Trade_SellItem_RefundsCreditsAndClearsSlot", World_Trade_SellItem_RefundsCreditsAndClearsSlot),
        ("World_Trade_BuyAndSell_FailWhileNotDocked", World_Trade_BuyAndSell_FailWhileNotDocked),
        ("World_Quest_Accept_SetsDestinationDifferentFromCurrentStation", World_Quest_Accept_SetsDestinationDifferentFromCurrentStation),
        ("World_Quest_Accept_FailsWhenAlreadyActive", World_Quest_Accept_FailsWhenAlreadyActive),
        ("World_Quest_TurnIn_FailsAtWrongStation", World_Quest_TurnIn_FailsAtWrongStation),
        ("World_Quest_TurnIn_AtDestination_AwardsCreditsAndClearsQuest", World_Quest_TurnIn_AtDestination_AwardsCreditsAndClearsQuest),
        ("World_Quest_Abandon_ClearsQuestAndCostsIssuerStanding", World_Quest_Abandon_ClearsQuestAndCostsIssuerStanding),
        ("World_Quest_Accept_FailsWhileNotDocked", World_Quest_Accept_FailsWhileNotDocked),
        ("World_MedKit_TakeFromRack_AddsToInventory", World_MedKit_TakeFromRack_AddsToInventory),
        ("World_MedKit_HealsSelfAndConsumesItem", World_MedKit_HealsSelfAndConsumesItem),
        ("World_MedKit_DoesNothingAtFullHealth", World_MedKit_DoesNothingAtFullHealth),
        ("World_Bleeding_DrainsHealthFasterThanDecompressionAlone", World_Bleeding_DrainsHealthFasterThanDecompressionAlone),
        ("World_Upgrade_PurchaseReactorOutput_IncreasesMaxOutputAndDeductsCredits", World_Upgrade_PurchaseReactorOutput_IncreasesMaxOutputAndDeductsCredits),
        ("World_Upgrade_Purchase_FailsWithoutEnoughCredits", World_Upgrade_Purchase_FailsWithoutEnoughCredits),
        ("World_Upgrade_Purchase_FailsWhileNotDocked", World_Upgrade_Purchase_FailsWhileNotDocked),
        ("World_Upgrade_WeaponDamage_IncreasesShotDamage", World_Upgrade_WeaponDamage_IncreasesShotDamage),
        ("World_Wiring_LayBackup_KeepsSystemPoweredAfterTrunkCut", World_Wiring_LayBackup_KeepsSystemPoweredAfterTrunkCut),
        ("World_Wiring_ShieldsOneDropCut_HalvesEffectivePower", World_Wiring_ShieldsOneDropCut_HalvesEffectivePower),
        ("World_Wiring_RepairingOneMultiDeviceUnit_DoesNotRepairItsSibling", World_Wiring_RepairingOneMultiDeviceUnit_DoesNotRepairItsSibling),
        ("World_WireLay_ConnectsTwoCompatiblePins_CreatesWireAndConsumesSpool", World_WireLay_ConnectsTwoCompatiblePins_CreatesWireAndConsumesSpool),
        ("World_WireLay_IncompatiblePinTypes_RejectsConnection", World_WireLay_IncompatiblePinTypes_RejectsConnection),
        ("World_WireLay_InputPinAtCapacity_RejectsThirdWire", World_WireLay_InputPinAtCapacity_RejectsThirdWire),
        ("World_WireLay_CancelPressed_ClearsPendingLayWithoutConsumingSpool", World_WireLay_CancelPressed_ClearsPendingLayWithoutConsumingSpool),
        ("World_WireLay_ClickingSamePinTwice_CancelsPendingLay", World_WireLay_ClickingSamePinTwice_CancelsPendingLay),
        ("World_WireLay_OtherPlayersSeeIsLayingWireFlagWhilePending", World_WireLay_OtherPlayersSeeIsLayingWireFlagWhilePending),
        ("World_WireLay_BendPoint_CarriesOntoFinishedWire", World_WireLay_BendPoint_CarriesOntoFinishedWire),
        ("World_WireLay_CancelPressed_RemovesBendsBeforeTheAnchorItself", World_WireLay_CancelPressed_RemovesBendsBeforeTheAnchorItself),
        ("World_Junction_BecomesDamagedOnTrunkCut_AndRepairsWithWrenchHeldInHand", World_Junction_BecomesDamagedOnTrunkCut_AndRepairsWithWrenchHeldInHand),
        ("World_Component_GateAnd_OutputsTrueOnlyWhenBothInputsTrue", World_Component_GateAnd_OutputsTrueOnlyWhenBothInputsTrue),
        ("World_Component_GateOr_OutputsTrueWhenEitherInputTrue", World_Component_GateOr_OutputsTrueWhenEitherInputTrue),
        ("World_Component_GateNot_InvertsInput", World_Component_GateNot_InvertsInput),
        ("World_Component_GateXor_OutputsTrueWhenInputsDiffer", World_Component_GateXor_OutputsTrueWhenInputsDiffer),
        ("World_Component_Timer_DelaysOutputUntilTriggerHeldLongEnough", World_Component_Timer_DelaysOutputUntilTriggerHeldLongEnough),
        ("World_Component_Timer_ResetsElapsedWhenTriggerGoesFalse", World_Component_Timer_ResetsElapsedWhenTriggerGoesFalse),
        ("World_Component_Memory_LatchesOnSetAndHoldsUntilReset", World_Component_Memory_LatchesOnSetAndHoldsUntilReset),
        ("World_Component_Memory_ResetWinsWhenSetAndResetBothTrue", World_Component_Memory_ResetWinsWhenSetAndResetBothTrue),
        ("World_Component_Relay_TogglesOnInteractAndDrivesWiredGate", World_Component_Relay_TogglesOnInteractAndDrivesWiredGate),
        ("World_ComponentLogic_CycleOfTwoNotGates_SettlesOrOscillatesWithinBoundedPasses", World_ComponentLogic_CycleOfTwoNotGates_SettlesOrOscillatesWithinBoundedPasses),
        ("World_Component_OxygenSensor_FiresWhenRoomOxygenLow", World_Component_OxygenSensor_FiresWhenRoomOxygenLow),
        ("World_Component_BreachSensor_FiresWhileRoomHasBreach", World_Component_BreachSensor_FiresWhileRoomHasBreach),
        ("World_Component_PowerLossSensor_FiresWhenReactorHasNoFuel", World_Component_PowerLossSensor_FiresWhenReactorHasNoFuel),
        ("World_Component_MotionSensor_FiresWhileCharacterInRoom", World_Component_MotionSensor_FiresWhileCharacterInRoom),
        ("World_Component_AutoDoorController_OpensDoorWhenSignalTrue", World_Component_AutoDoorController_OpensDoorWhenSignalTrue),
        ("World_Component_AlarmAndLightActuators_ReflectWiredSignalInState", World_Component_AlarmAndLightActuators_ReflectWiredSignalInState),
        ("World_ComponentMount_InstallFromHeldItem_AddsComponentAndClearsHeldItem", World_ComponentMount_InstallFromHeldItem_AddsComponentAndClearsHeldItem),
        ("World_ComponentMount_Uninstall_ReturnsItemAndRemovesAttachedWires", World_ComponentMount_Uninstall_ReturnsItemAndRemovesAttachedWires),
        ("World_ComponentMount_RelayTogglesWithoutStartingWireLay", World_ComponentMount_RelayTogglesWithoutStartingWireLay),
        ("World_ShipPurchase_ResetsComponentMountsAndWiring", World_ShipPurchase_ResetsComponentMountsAndWiring),
        ("World_Storage_RackStartsWithThreeOfEachStarterItemAcrossTwoShelves", World_Storage_RackStartsWithThreeOfEachStarterItemAcrossTwoShelves),
        ("World_Storage_RackResetsOnShipPurchase", World_Storage_RackResetsOnShipPurchase),
        ("World_Helm_Thrust_AcceleratesShipWithInertia", World_Helm_Thrust_AcceleratesShipWithInertia),
        ("World_Helm_WasdSteersByHeadingAndReverseBacksOut", World_Helm_WasdSteersByHeadingAndReverseBacksOut),
        ("World_Helm_ThrustPersists_AfterStandingUp", World_Helm_ThrustPersists_AfterStandingUp),
        ("World_Helm_Stabilize_BringsShipToStop", World_Helm_Stabilize_BringsShipToStop),
        ("World_Helm_NoEnginePower_ShipDoesNotAccelerate", World_Helm_NoEnginePower_ShipDoesNotAccelerate),
        ("World_Ship_CollidesWithAsteroid_StopsShipAndBreachesHull", World_Ship_CollidesWithAsteroid_StopsShipAndBreachesHull),
        ("AsteroidShape_IsAStableNonCircularOutline", AsteroidShape_IsAStableNonCircularOutline),
        ("HullSilhouette_TreatsTheGapBetweenPylonsAsOpenSpace", HullSilhouette_TreatsTheGapBetweenPylonsAsOpenSpace),
        ("World_ToggleDoor_ViaClientCommand_FlipsState", World_ToggleDoor_ViaClientCommand_FlipsState),
        ("World_Door_Destroyed_ForcesOpenAndBlocksClosing", World_Door_Destroyed_ForcesOpenAndBlocksClosing),
        ("World_Door_Repair_RestoresItAndAllowsClosingAgain", World_Door_Repair_RestoresItAndAllowsClosingAgain),
        ("World_Door_Closed_BlocksMovementLikeWall", World_Door_Closed_BlocksMovementLikeWall),
        ("World_AirlockOuterDoor_Open_LeaksChamberToVacuum", World_AirlockOuterDoor_Open_LeaksChamberToVacuum),
        ("World_AirlockOuterDoor_Closed_ChamberStaysPressurized", World_AirlockOuterDoor_Closed_ChamberStaysPressurized),
        ("World_ClosedInnerDoor_KeepsRestOfShipSealedFromVentedChamber", World_ClosedInnerDoor_KeepsRestOfShipSealedFromVentedChamber),
        ("World_OpenInnerDoor_LetsVentedChamberDrainRestOfShip", World_OpenInnerDoor_LetsVentedChamberDrainRestOfShip),
        ("World_Eva_ExitUnsuited_AllowedButFatalAfterGrace", World_Eva_ExitUnsuited_AllowedButFatalAfterGrace),
        ("World_Eva_ExitSuited_SetsIsOutsideAndAttachesToShip", World_Eva_ExitSuited_SetsIsOutsideAndAttachesToShip),
        ("World_Eva_AttachedToShip_MovesWithShipWhenShipMoves", World_Eva_AttachedToShip_MovesWithShipWhenShipMoves),
        ("World_Eva_PushOff_BecomesFreeFloatingWithVelocity", World_Eva_PushOff_BecomesFreeFloatingWithVelocity),
        ("World_Eva_Jetpack_ExhaustsFuelThenKeepsDriftingAtLastVelocity", World_Eva_Jetpack_ExhaustsFuelThenKeepsDriftingAtLastVelocity),
        ("World_Eva_AutoReattachToShip_WhenDriftingBack", World_Eva_AutoReattachToShip_WhenDriftingBack),
        ("World_Eva_ReenterShip_ReturnsInsideAtAirlockChamber", World_Eva_ReenterShip_ReturnsInsideAtAirlockChamber),
        ("World_Weld_SurvivesAnEvaRoundTripWithoutLosingUnrelatedCharge", World_Weld_SurvivesAnEvaRoundTripWithoutLosingUnrelatedCharge),
        ("World_Rack_DragFromInventory_StowsItem", World_Rack_DragFromInventory_StowsItem),
        ("World_Rack_DropOntoOccupiedSlot_SwapsTheTwo", World_Rack_DropOntoOccupiedSlot_SwapsTheTwo),
        ("World_Rack_AwayFromTheRack_MoveIsRefused", World_Rack_AwayFromTheRack_MoveIsRefused),
        ("World_Inventory_DragBetweenOwnSlots_MovesAndEmptiesHands", World_Inventory_DragBetweenOwnSlots_MovesAndEmptiesHands),
        ("World_Save_RoundTripsRackContents", World_Save_RoundTripsRackContents),
        ("World_Eva_MagnetizedWalk_StaysFlushAgainstTheHull", World_Eva_MagnetizedWalk_StaysFlushAgainstTheHull),
        ("World_Eva_WalkingAwayFromTheDoor_StaysOutside", World_Eva_WalkingAwayFromTheDoor_StaysOutside),
        ("World_Eva_BootsGrabOnContact_NotAcrossTheGap", World_Eva_BootsGrabOnContact_NotAcrossTheGap),
        ("World_Mining_CutterFlameBreaksBlockIntoPickableItem", World_Mining_CutterFlameBreaksBlockIntoPickableItem),
        ("World_Mining_CutterWithoutTank_CutsNothing", World_Mining_CutterWithoutTank_CutsNothing),
        ("World_Mining_CutBlock_DropsOnceAndIsGone", World_Mining_CutBlock_DropsOnceAndIsGone),
        ("World_Welding_WithoutTank_WeldsNothing", World_Welding_WithoutTank_WeldsNothing),
        ("World_WallCutter_DamagesGraduallyBeforeBreaching", World_WallCutter_DamagesGraduallyBeforeBreaching),
        ("World_Cut_BreachesOwnHullFromOutside", World_Cut_BreachesOwnHullFromOutside),
        ("World_WeldHealthyWall_RevealsHpWithoutChangingIt", World_WeldHealthyWall_RevealsHpWithoutChangingIt),
        ("World_StationWall_WeldRevealsHpWithoutChangingIt", World_StationWall_WeldRevealsHpWithoutChangingIt),
        ("World_Eva_SingleBrokenBlock_IsNotPassable", World_Eva_SingleBrokenBlock_IsNotPassable),
        ("World_Eva_TwoAdjacentBrokenBlocks_ArePassable", World_Eva_TwoAdjacentBrokenBlocks_ArePassable),
        ("World_Eva_PassableInteriorBreach_WalksIntoAdjacentRoomNotVacuum", World_Eva_PassableInteriorBreach_WalksIntoAdjacentRoomNotVacuum),
        ("World_TankSockets_WrongTankTypeIsRejected", World_TankSockets_WrongTankTypeIsRejected),
        ("World_Eva_SuitWithoutTank_SurvivesOnlyTheGracePeriod", World_Eva_SuitWithoutTank_SurvivesOnlyTheGracePeriod),
        ("World_Eva_SuitTankRunsDownInVacuum", World_Eva_SuitTankRunsDownInVacuum),
        ("World_Mining_SellMineralAtStation_RefundsCreditsAndClearsSlot", World_Mining_SellMineralAtStation_RefundsCreditsAndClearsSlot),
        ("World_Storage_DropItem_LandsOnFloorAndClearsSlot", World_Storage_DropItem_LandsOnFloorAndClearsSlot),
        ("World_Storage_DropItem_UnreachableRackSlotIsRefused", World_Storage_DropItem_UnreachableRackSlotIsRefused),
        ("World_Storage_DropItem_DetachesTankBeforeDropping", World_Storage_DropItem_DetachesTankBeforeDropping),
        ("World_Storage_PickupDroppedItem_ReturnsItToInventory", World_Storage_PickupDroppedItem_ReturnsItToInventory),
        ("World_Storage_PickupDroppedItem_TooFarAwayIsRefused", World_Storage_PickupDroppedItem_TooFarAwayIsRefused),
        ("World_Mining_ClickPickup_WorksSameAsInteractKey", World_Mining_ClickPickup_WorksSameAsInteractKey),
        ("Ship_Scout_HasAirlockChamberAndSameWireDeviceIds", Ship_Scout_HasAirlockChamberAndSameWireDeviceIds),
        ("Ship_Corvette_HasSideGunsTwoPortsAndSameWireDeviceIds", Ship_Corvette_HasSideGunsTwoPortsAndSameWireDeviceIds),
        ("Ship_Corvette_CrewWalksTheSpineAndOutToBothBays", Ship_Corvette_CrewWalksTheSpineAndOutToBothBays),
        ("World_Eva_CorvetteCrewGoesOutThroughABeamPort", World_Eva_CorvetteCrewGoesOutThroughABeamPort),
        ("World_ShipField_CorvetteFliesNoseFirst", World_ShipField_CorvetteFliesNoseFirst),
        ("Ship_Cruiser_HasAirlockChamberAndThreeTurrets", Ship_Cruiser_HasAirlockChamberAndThreeTurrets),
        ("World_ShipKindScout_SpawnsAndSteps", World_ShipKindScout_SpawnsAndSteps),
        ("World_ShipKindCruiser_SpawnsAndSteps", World_ShipKindCruiser_SpawnsAndSteps),
        ("RoomLayout_MoveAlongAxis_BlocksAtWallWithoutDoor", RoomLayout_MoveAlongAxis_BlocksAtWallWithoutDoor),
        ("World_Station_ArrivingNearStationDoesNotAutoDock", World_Station_ArrivingNearStationDoesNotAutoDock),
        ("World_Station_DockAtStation_ReachesStationPhase", World_Station_DockAtStation_ReachesStationPhase),
        ("World_Station_WalkThroughOpenOuterDoor_EntersStation", World_Station_WalkThroughOpenOuterDoor_EntersStation),
        ("World_Station_WalkBackThroughConnector_ReturnsToShip", World_Station_WalkBackThroughConnector_ReturnsToShip),
        ("World_Station_OuterDoorWhileNotDocked_EntersVacuumNotStation", World_Station_OuterDoorWhileNotDocked_EntersVacuumNotStation),
        ("World_Boarding_EvaDuringBattle_ReachesEnemyShip", World_Boarding_EvaDuringBattle_ReachesEnemyShip),
        ("World_Boarding_FireWeaponDamagesCrewInSameRoom", World_Boarding_FireWeaponDamagesCrewInSameRoom),
        ("World_Boarding_WithoutWeaponHeld_DoesNothing", World_Boarding_WithoutWeaponHeld_DoesNothing),
        ("World_Boarding_KillingAllCrew_DestroysEnemyShip", World_Boarding_KillingAllCrew_DestroysEnemyShip),
        ("World_Boarding_CrewFightsBack_DamagesBoarder", World_Boarding_CrewFightsBack_DamagesBoarder),
        ("EnemyShipClasses_AreDistinctStructures", EnemyShipClasses_AreDistinctStructures),
        ("EnemyShipClasses_FrigateMatchesCorvetteFootprintAndCarriesItsFixedGuns", EnemyShipClasses_FrigateMatchesCorvetteFootprintAndCarriesItsFixedGuns),
        ("World_Boarding_SectorAlwaysFieldsTheSameHull", World_Boarding_SectorAlwaysFieldsTheSameHull),
        ("World_Boarding_MagneticBootsAttachToEnemyHull", World_Boarding_MagneticBootsAttachToEnemyHull),
        ("World_Boarding_IndoorCuttingDamagesEnemyDoor", World_Boarding_IndoorCuttingDamagesEnemyDoor),
        ("World_Boarding_IndoorWeldingRepairsBreachedEnemyWallBlock", World_Boarding_IndoorWeldingRepairsBreachedEnemyWallBlock),
        ("World_Boarding_CuttingEnemyHullDamagesIt", World_Boarding_CuttingEnemyHullDamagesIt),
        ("World_Boarding_CrossingACutHullBreachBoardsIntoThatRoom", World_Boarding_CrossingACutHullBreachBoardsIntoThatRoom),
        ("World_Boarding_OpeningDoors_VentsTheHullAndSuffocatesUnsuitedCrew", World_Boarding_OpeningDoors_VentsTheHullAndSuffocatesUnsuitedCrew),
        ("World_Boarding_HullDestroyedUnderneath_EjectsTheBoardingParty", World_Boarding_HullDestroyedUnderneath_EjectsTheBoardingParty),
        ("World_Faction_DestroyingShip_LowersOwnerRaisesRival", World_Faction_DestroyingShip_LowersOwnerRaisesRival),
        ("World_Faction_QuestTurnIn_RaisesStanding", World_Faction_QuestTurnIn_RaisesStanding),
        ("World_Faction_QuestTurnIn_LowersRivalStanding", World_Faction_QuestTurnIn_LowersRivalStanding),
        ("World_Faction_HostileStanding_BlocksQuestOffers", World_Faction_HostileStanding_BlocksQuestOffers),
        ("World_Faction_HostileStanding_RaisesPrices", World_Faction_HostileStanding_RaisesPrices),
        ("World_Faction_HostileStanding_SendsABiggerSquadron", World_Faction_HostileStanding_SendsABiggerSquadron),
        ("World_Faction_War_ContestedStationFlipsAfterEnoughShipsDestroyed", World_Faction_War_ContestedStationFlipsAfterEnoughShipsDestroyed),
        ("World_Docking_AtWar_NeverArmsTheButton", World_Docking_AtWar_NeverArmsTheButton),
        ("World_Faction_IndependentsNeverShift", World_Faction_IndependentsNeverShift),
        ("World_Faction_MinersGuildNeverHasARival", World_Faction_MinersGuildNeverHasARival),
        ("World_Trade_SellMineralAtMiningStation_PaysBonusOverListPrice", World_Trade_SellMineralAtMiningStation_PaysBonusOverListPrice),
        ("World_Shipyard_BuyCheaperHull_SwapsShipAndRefunds", World_Shipyard_BuyCheaperHull_SwapsShipAndRefunds),
        ("World_Shipyard_Buy_FailsWithoutEnoughCredits", World_Shipyard_Buy_FailsWithoutEnoughCredits),
        ("World_Shipyard_Buy_FailsWhileNotDocked", World_Shipyard_Buy_FailsWhileNotDocked),
        ("World_Shipyard_SwapKeepsCreditsAndClearsBreaches", World_Shipyard_SwapKeepsCreditsAndClearsBreaches),
        ("World_ShipBuilding_BuildsWhenRequested_AddsRoomAndDeductsCreditsAndPlating", World_ShipBuilding_BuildsWhenRequested_AddsRoomAndDeductsCreditsAndPlating),
        ("World_ShipBuilding_BuildIsNotInstant_ShowsAsPendingGhostUntilComplete", World_ShipBuilding_BuildIsNotInstant_ShowsAsPendingGhostUntilComplete),
        ("World_ShipBuilding_SucceedsWhileUndockedAndAwayFromAnyShipwright", World_ShipBuilding_SucceedsWhileUndockedAndAwayFromAnyShipwright),
        ("World_ShipBuilding_FailsWithoutEnoughCredits", World_ShipBuilding_FailsWithoutEnoughCredits),
        ("World_ShipBuilding_FailsWithoutEnoughPlating", World_ShipBuilding_FailsWithoutEnoughPlating),
        ("World_ShipBuilding_FailsForUnknownCatalogId", World_ShipBuilding_FailsForUnknownCatalogId),
        ("World_ShipBuilding_SecondPendingBuild_DoesNotOverlapTheFirstGhost", World_ShipBuilding_SecondPendingBuild_DoesNotOverlapTheFirstGhost),
        ("World_ShipBuilding_ExplicitPosition_BuildsExactlyThere", World_ShipBuilding_ExplicitPosition_BuildsExactlyThere),
        ("World_ShipBuilding_ExplicitPosition_RefusesFloatingPlacementWithoutCharge", World_ShipBuilding_ExplicitPosition_RefusesFloatingPlacementWithoutCharge),
        ("World_ShipBuilding_NewRoomOxygenAndDoorsInitialize", World_ShipBuilding_NewRoomOxygenAndDoorsInitialize),
        ("World_ShipBuilding_ToDefinitionRoundTrip_PreservesEveryHandAuthoredHull", World_ShipBuilding_ToDefinitionRoundTrip_PreservesEveryHandAuthoredHull),
        ("RoomGraphConnectivity_DetectsConnectedAndDisconnectedGraphs", RoomGraphConnectivity_DetectsConnectedAndDisconnectedGraphs),
        ("World_ShipBuilding_BuildRoom_PreservesExistingWireDamage", World_ShipBuilding_BuildRoom_PreservesExistingWireDamage),
        ("World_ShipBuilding_BuildRoom_PreservesWallBlockHpAndInitializesNewRoom", World_ShipBuilding_BuildRoom_PreservesWallBlockHpAndInitializesNewRoom),
        ("World_ShipBuilding_BuildRoom_PreservesClosedDoorState", World_ShipBuilding_BuildRoom_PreservesClosedDoorState),
        ("World_ShipBuilding_DemolishRoom_RemovesTheRoom", World_ShipBuilding_DemolishRoom_RemovesTheRoom),
        ("World_ShipBuilding_DemolishRoom_BlockedWhenRoomHoldsSoleReactor", World_ShipBuilding_DemolishRoom_BlockedWhenRoomHoldsSoleReactor),
        ("World_ShipBuilding_DemolishRoom_FailsWhenNotDocked", World_ShipBuilding_DemolishRoom_FailsWhenNotDocked),
        ("World_ShipBuilding_DemolishRoom_FailsAtStationWithoutShipwright", World_ShipBuilding_DemolishRoom_FailsAtStationWithoutShipwright),
        ("World_ShipDebris_DestroyingRoomsOwnWallBlocks_DetachesItAsDebris", World_ShipDebris_DestroyingRoomsOwnWallBlocks_DetachesItAsDebris),
        ("World_ShipDebris_DriftsByInertiaAfterDetaching", World_ShipDebris_DriftsByInertiaAfterDetaching),
        ("World_ShipDebris_EjectsCrewAndDropsItemsWhenRoomDetaches", World_ShipDebris_EjectsCrewAndDropsItemsWhenRoomDetaches),
        ("World_ShipDebris_DestroyingReactorRoom_StaysAttachedNoDebris", World_ShipDebris_DestroyingReactorRoom_StaysAttachedNoDebris),
        ("World_ShipDebris_DestroyingRoomThatWouldInvalidateTheHull_StaysAttached", World_ShipDebris_DestroyingRoomThatWouldInvalidateTheHull_StaysAttached),
        ("World_ContentCatalog_ReactorRoom_IncreasesOutputBonus", World_ContentCatalog_ReactorRoom_IncreasesOutputBonus),
        ("World_ContentCatalog_TwoReactorRooms_BonusesSum", World_ContentCatalog_TwoReactorRooms_BonusesSum),
        ("World_ContentCatalog_DestroyingReactorRoom_LowersBonusBack", World_ContentCatalog_DestroyingReactorRoom_LowersBonusBack),
        ("World_ContentCatalog_ShieldGeneratorRoom_IncreasesMaxPoints", World_ContentCatalog_ShieldGeneratorRoom_IncreasesMaxPoints),
        ("World_ContentCatalog_EngineRoom_CarriesThrustBonusOntoADevice", World_ContentCatalog_EngineRoom_CarriesThrustBonusOntoADevice),
        ("World_ContentCatalog_RcsRoom_CarriesTurnBonusOntoADevice", World_ContentCatalog_RcsRoom_CarriesTurnBonusOntoADevice),
        ("World_ContentCatalog_TurretRoom_BuildsAWorkingTurret", World_ContentCatalog_TurretRoom_BuildsAWorkingTurret),
        ("World_ContentCatalog_CameraRoom_BuildsAWorkingCamera", World_ContentCatalog_CameraRoom_BuildsAWorkingCamera),
        ("World_ContentCatalog_CockpitRoom_AddsExtraHelmAndNavigationConsoles", World_ContentCatalog_CockpitRoom_AddsExtraHelmAndNavigationConsoles),
        ("World_ContentCatalog_ExtraHelmSeat_LetsACharacterPilot", World_ContentCatalog_ExtraHelmSeat_LetsACharacterPilot),
        ("CustomShipValidator_AllowsMultipleReactorsHelmsAndNavigationConsoles", CustomShipValidator_AllowsMultipleReactorsHelmsAndNavigationConsoles),
        ("World_Quest_Bounty_CompletesOnKillAndPaysAtIssuer", World_Quest_Bounty_CompletesOnKillAndPaysAtIssuer),
        ("World_Quest_Bounty_TurnIn_FailsBeforeKill", World_Quest_Bounty_TurnIn_FailsBeforeKill),
        ("World_Quest_Mining_ConsumesOreAndPays", World_Quest_Mining_ConsumesOreAndPays),
        ("World_Quest_Mining_TurnIn_FailsWithoutEnoughOre", World_Quest_Mining_TurnIn_FailsWithoutEnoughOre),
        ("World_Save_RoundTripsCampaignProgress", World_Save_RoundTripsCampaignProgress),
        ("World_Save_AutosavePendingSetOnDocking", World_Save_AutosavePendingSetOnDocking),
        ("SaveStore_RoundTripsThroughFile", SaveStore_RoundTripsThroughFile),
        ("SaveStore_MissingOrCorruptFile_LoadsAsNoSave", SaveStore_MissingOrCorruptFile_LoadsAsNoSave),
        ("GameServer_AutosavesOnDocking", GameServer_AutosavesOnDocking),
        ("World_Crime_StealCrate_AddsItemAndMarksLooted", World_Crime_StealCrate_AddsItemAndMarksLooted),
        ("World_Crime_CaughtByGuard_FinesConfiscatesAndLowersStanding", World_Crime_CaughtByGuard_FinesConfiscatesAndLowersStanding),
        ("World_Crime_UnseenTheft_GoesUnpunished", World_Crime_UnseenTheft_GoesUnpunished),
        ("World_Crime_ShootingGuard_AlertsStationAndGuardFightsBack", World_Crime_ShootingGuard_AlertsStationAndGuardFightsBack),
        ("World_Crime_KillingGuard_CostsHeavyStanding", World_Crime_KillingGuard_CostsHeavyStanding),
        ("World_Crime_RedockingRestocksCrates", World_Crime_RedockingRestocksCrates),
        ("World_Squadron_NextShipEngagesAfterEachKill", World_Squadron_NextShipEngagesAfterEachKill),
        ("World_Squadron_EveryKillCostsOwnerStanding", World_Squadron_EveryKillCostsOwnerStanding),
        ("World_Squadron_BountyCompletesOnlyWhenSectorCleared", World_Squadron_BountyCompletesOnlyWhenSectorCleared),
        ("World_Docking_ProximityAloneDoesNotDock", World_Docking_ProximityAloneDoesNotDock),
        ("World_Docking_ButtonFarFromPort_DoesNothing", World_Docking_ButtonFarFromPort_DoesNothing),
        ("World_Docking_TooFastAtPort_ButtonStaysDisarmed", World_Docking_TooFastAtPort_ButtonStaysDisarmed),
        ("World_Docking_StationHullBlocksTheShip", World_Docking_StationHullBlocksTheShip),
        ("World_Docking_ButtonUndocksWhenPressedWhileAlreadyDocked", World_Docking_ButtonUndocksWhenPressedWhileAlreadyDocked),
        ("World_Docking_UndockButtonPullsCrewBackAboard", World_Docking_UndockButtonPullsCrewBackAboard),
        ("World_Docking_MatesAirlockOntoStationConnector", World_Docking_MatesAirlockOntoStationConnector),
        ("World_Station_CrossingConnector_MovesContinuously", World_Station_CrossingConnector_MovesContinuously),
        ("World_Station_Departing_PullsCrewBackAboard", World_Station_Departing_PullsCrewBackAboard),
        ("World_Station_OpenAirlockWhileDocked_DoesNotVentTheShip", World_Station_OpenAirlockWhileDocked_DoesNotVentTheShip),
        ("Wire_SnapshotSurvivesTheRoundTrip", Wire_SnapshotSurvivesTheRoundTrip),
        ("Wire_FramesAreSelfDelimitingOnOneStream", Wire_FramesAreSelfDelimitingOnOneStream),
        ("Wire_SnapshotFrameStaysWithinBudget", Wire_SnapshotFrameStaysWithinBudget),
        ("Coop_JoinerGetsOwnCharacterAndDrivesItOverTheSocket", Coop_JoinerGetsOwnCharacterAndDrivesItOverTheSocket),
        ("Coop_DroppedConnection_TakesItsCharacterOffTheShip", Coop_DroppedConnection_TakesItsCharacterOffTheShip),
        ("Coop_GunnerLeavingUnmansTheTurret", Coop_GunnerLeavingUnmansTheTurret),
        ("World_Recruiting_RosterOffersCandidatesAtHomeStation", World_Recruiting_RosterOffersCandidatesAtHomeStation),
        ("World_Recruiting_HireDeductsCreditsAndAddsBotToCrew", World_Recruiting_HireDeductsCreditsAndAddsBotToCrew),
        ("World_Recruiting_HireFailsForUnknownCandidateId", World_Recruiting_HireFailsForUnknownCandidateId),
        ("World_Recruiting_HireFailsWithoutEnoughCredits", World_Recruiting_HireFailsWithoutEnoughCredits),
        ("World_Recruiting_HireFailsWhileNotDocked", World_Recruiting_HireFailsWhileNotDocked),
        ("World_Recruiting_RespectsMaxHiredBotsCap", World_Recruiting_RespectsMaxHiredBotsCap),
        ("World_Recruiting_SecurityBotAutoMansAndFiresAtEnemy", World_Recruiting_SecurityBotAutoMansAndFiresAtEnemy),
        ("World_Recruiting_MechanicBotRefuelsDrainedReactor", World_Recruiting_MechanicBotRefuelsDrainedReactor),
        ("World_Recruiting_ScientistBotLeavesHealthyCrewAlone", World_Recruiting_ScientistBotLeavesHealthyCrewAlone),
        ("World_Recruiting_EngineerBotFeedsUnpoweredSystems", World_Recruiting_EngineerBotFeedsUnpoweredSystems),
        ("World_Recruiting_CaptainBotStabilizesAbandonedHelm", World_Recruiting_CaptainBotStabilizesAbandonedHelm),
        ("World_StarSystem_GalaxyHasMoreThanOneSystemFromTheStart", World_StarSystem_GalaxyHasMoreThanOneSystemFromTheStart),
        ("World_StarSystem_FlyToWarpZoneThenJumpToOtherSystem", World_StarSystem_FlyToWarpZoneThenJumpToOtherSystem),
        ("World_StarSystem_WarpDoesNothingOutsideTheWarpZone", World_StarSystem_WarpDoesNothingOutsideTheWarpZone),
        ("World_StarSystem_WarpFailsOutsideWarpRadius", World_StarSystem_WarpFailsOutsideWarpRadius),
        ("World_StarSystem_ArrivesAtEdgeOfNewSystemAndCanContinueWarping", World_StarSystem_ArrivesAtEdgeOfNewSystemAndCanContinueWarping),
        ("World_StarSystem_GalaxyIsFullyReachableByWarpRadius", World_StarSystem_GalaxyIsFullyReachableByWarpRadius),
        ("World_Campaign_StartsWithDeliveryQuestAssigned", World_Campaign_StartsWithDeliveryQuestAssigned),
        ("World_Campaign_StartCampaignIsIdempotent", World_Campaign_StartCampaignIsIdempotent),
        ("World_Campaign_AbandoningStoryQuestDoesNotAdvanceStage", World_Campaign_AbandoningStoryQuestDoesNotAdvanceStage),
        ("World_Campaign_FullChainReachesComplete", World_Campaign_FullChainReachesComplete),
        ("World_CardGame_TwoPlayersAtTableStartAHand", World_CardGame_TwoPlayersAtTableStartAHand),
        ("World_CardGame_OnlyOnePlayerAtTableDoesNotStart", World_CardGame_OnlyOnePlayerAtTableDoesNotStart),
        ("World_CardGame_WalkingAwayCancelsTheHand", World_CardGame_WalkingAwayCancelsTheHand),
        ("World_Tutorial_AdvancesThroughAllFourStepsToComplete", World_Tutorial_AdvancesThroughAllFourStepsToComplete),
        ("World_Tutorial_NeverActiveOnAnOrdinaryCampaignRun", World_Tutorial_NeverActiveOnAnOrdinaryCampaignRun),
        ("CustomShip_Validator_RejectsBlankDefinition", CustomShip_Validator_RejectsBlankDefinition),
        ("CustomShip_Validator_AcceptsSimpleValidDefinition", CustomShip_Validator_AcceptsSimpleValidDefinition),
        ("CustomShip_FromDefinition_BuildsRoomsDoorsAndAirlock", CustomShip_FromDefinition_BuildsRoomsDoorsAndAirlock),
        ("CustomShip_FromDefinition_SkipsWallBlocksOnInteriorAndAirlockSides", CustomShip_FromDefinition_SkipsWallBlocksOnInteriorAndAirlockSides),
        ("CustomShip_World_CharacterWalksThroughPlacedDoor", CustomShip_World_CharacterWalksThroughPlacedDoor),
        ("CustomShip_World_SnapshotCarriesCustomKindAndForwardDegrees", CustomShip_World_SnapshotCarriesCustomKindAndForwardDegrees),
        // Appended at the end, not inlined next to the other ammo/turret tests above - every World()
        // instance created anywhere in the suite draws from one shared incrementing seed counter
        // (World.cs), so inserting a new test earlier in this list shifts the exact RNG sequence
        // every later test's World gets. Adding new World-creating tests only at the tail leaves
        // every existing test's seed untouched.
        ("World_AmmoStorage_StockIsFiniteAndDepletes", World_AmmoStorage_StockIsFiniteAndDepletes),
        ("World_AmmoStorage_RestocksAtStation", World_AmmoStorage_RestocksAtStation),
        ("World_Axe_ChopsClosedDoorInTwoHits", World_Axe_ChopsClosedDoorInTwoHits),
        ("World_Axe_DoesNothingWithoutAxeInHand", World_Axe_DoesNothingWithoutAxeInHand),
        ("World_StarSystem_GalaxyHas200SystemsAllReachable", World_StarSystem_GalaxyHas200SystemsAllReachable),
        ("World_StarSystem_MostProceduralSystemsHaveAControllingFaction", World_StarSystem_MostProceduralSystemsHaveAControllingFaction),
        ("World_StarSystem_ControlledSystemsGetFewerHostileSectorsThanContested", World_StarSystem_ControlledSystemsGetFewerHostileSectorsThanContested),
        ("World_StarSystem_ChunkedGenerationMatchesWhicheverPacingReachesIt", World_StarSystem_ChunkedGenerationMatchesWhicheverPacingReachesIt),
        ("World_StarSystem_EnsureGeneratedGrowsUntilNeighborTargetIsMet", World_StarSystem_EnsureGeneratedGrowsUntilNeighborTargetIsMet),
        ("World_Station_HostileStandingTriggersDefensiveSquadronOnApproach", World_Station_HostileStandingTriggersDefensiveSquadronOnApproach),
        ("World_Equip_BeltBag_HoldsItemsInItsOwnSubSlots", World_Equip_BeltBag_HoldsItemsInItsOwnSubSlots),
        ("World_Equip_CannotUnequipNonEmptyBeltBag", World_Equip_CannotUnequipNonEmptyBeltBag),
        ("World_Equip_WrongItemTypeIsRefused", World_Equip_WrongItemTypeIsRefused),
        ("World_Equip_IdCardEquipsIntoItsOwnSlot", World_Equip_IdCardEquipsIntoItsOwnSlot),
        ("World_Eva_MagneticBoots_AttachToStationHull", World_Eva_MagneticBoots_AttachToStationHull),
        ("World_Eva_BootsOff_BouncesOffStationHull", World_Eva_BootsOff_BouncesOffStationHull),
        ("World_NpcShips_PopulateOnFirstStepAndStayWithinCap", World_NpcShips_PopulateOnFirstStepAndStayWithinCap),
        ("World_NpcShips_CargoShuttlesBetweenBothEndsOfItsRoute", World_NpcShips_CargoShuttlesBetweenBothEndsOfItsRoute),
        ("World_NpcShips_MilitaryTurnsHostileAndFightingItCostsStanding", World_NpcShips_MilitaryTurnsHostileAndFightingItCostsStanding),
        ("World_Scanner_SweepFindsShipInsideConeNotOutside", World_Scanner_SweepFindsShipInsideConeNotOutside),
        ("World_Scanner_ContactStaysAtLastKnownPositionAfterLeavingTheCone", World_Scanner_ContactStaysAtLastKnownPositionAfterLeavingTheCone),
        ("World_Scanner_DoesNothingAwayFromTheConsole", World_Scanner_DoesNothingAwayFromTheConsole),
        ("World_Scanner_PingDoesNothingWhileOnCooldown", World_Scanner_PingDoesNothingWhileOnCooldown),
        ("World_Scanner_CircularModeFindsShipRegardlessOfBearing", World_Scanner_CircularModeFindsShipRegardlessOfBearing),
        ("World_Scanner_CircularModeHasHalfTheDirectionalRange", World_Scanner_CircularModeHasHalfTheDirectionalRange),
        ("World_Scanner_PlacingMarkerAddsItToTheSharedMap", World_Scanner_PlacingMarkerAddsItToTheSharedMap),
        ("World_Scanner_ManualMarkerSurvivesSaveAndLoad", World_Scanner_ManualMarkerSurvivesSaveAndLoad),
        ("World_Cameras_EveryHandAuthoredHullHasWorkingCameraGeometry", World_Cameras_EveryHandAuthoredHullHasWorkingCameraGeometry),
        ("World_Cameras_StartConnectedAndAppearInSnapshot", World_Cameras_StartConnectedAndAppearInSnapshot),
        ("World_Cameras_CuttingOneCameraWireLeavesItsSiblingConnected", World_Cameras_CuttingOneCameraWireLeavesItsSiblingConnected),
        ("World_Cameras_RepairingWithWrenchReconnectsIt", World_Cameras_RepairingWithWrenchReconnectsIt),
        ("Station_Procedural_RoomCountStaysInTheAgreedBand", Station_Procedural_RoomCountStaysInTheAgreedBand),
        ("Station_Procedural_AlwaysHasTheMandatoryModules", Station_Procedural_AlwaysHasTheMandatoryModules),
        ("Station_Procedural_EveryRoomIsReachableFromTheDock", Station_Procedural_EveryRoomIsReachableFromTheDock),
        ("Station_Procedural_NoTwoRoomsOverlap", Station_Procedural_NoTwoRoomsOverlap),
        ("Station_Procedural_SamePointIdAlwaysRegeneratesIdentically", Station_Procedural_SamePointIdAlwaysRegeneratesIdentically),
        ("Station_Procedural_DifferentPointIdsGiveDifferentShapes", Station_Procedural_DifferentPointIdsGiveDifferentShapes),
        ("Station_Procedural_ConnectorLandsExactlyOnTheAnchor", Station_Procedural_ConnectorLandsExactlyOnTheAnchor),
        ("CelestialBodies_SameSystemIdAlwaysProducesIdenticalLayout", CelestialBodies_SameSystemIdAlwaysProducesIdenticalLayout),
        ("CelestialBodies_PlanetCountWithinAgreedBand", CelestialBodies_PlanetCountWithinAgreedBand),
        ("CelestialBodies_NoTwoBodiesOverlap", CelestialBodies_NoTwoBodiesOverlap),
        ("CelestialBodies_BeltGapsAreDeterministicAndWithinCount", CelestialBodies_BeltGapsAreDeterministicAndWithinCount),
        ("World_PlanetLanding_CanLandNow_TrueWhenTouchingLandableBody_FalseWhenFar", World_PlanetLanding_CanLandNow_TrueWhenTouchingLandableBody_FalseWhenFar),
        ("World_PlanetLanding_TryLand_EntersSurfaceFieldWithNoGravity", World_PlanetLanding_TryLand_EntersSurfaceFieldWithNoGravity),
        ("World_PlanetLanding_Obstacles_BlockShipMovement", World_PlanetLanding_Obstacles_BlockShipMovement),
        ("World_PlanetLanding_TakeOff_ReturnsToSystemFieldNearBodyPosition", World_PlanetLanding_TakeOff_ReturnsToSystemFieldNearBodyPosition),
        ("World_PlanetLanding_Eva_WalksOnSurfaceAndReturnsInside", World_PlanetLanding_Eva_WalksOnSurfaceAndReturnsInside),
    };

    // Throwaway diagnostic for one specific scenario - not a registered test, invoked only via
    // Program.cs's DIAG=1 env var switch while chasing a specific failure interactively.
    public static void Diagnostic()
    {
    }

    // Every test builds its own fresh World() (sometimes several, in a retry loop) with no shared
    // mutable state EXCEPT one thing: World.EnemyAi.cs/World.NpcShips.cs seed their own per-instance
    // combat/NPC RNGs off a shared counter, specifically so a full SEQUENTIAL run stays reproducible
    // (fixed construction order -> fixed seeds). Running the actual test bodies concurrently is
    // otherwise safe, but that one seed counter would start racing across threads instead of
    // following the fixed Tests order, silently turning "unlucky roll" tests flaky.
    // World.DebugDeterministicSeedBase (set per-thread to this test's own fixed array index, and
    // reset right after) restores the exact same guarantee under parallel execution - see its own
    // doc comment in World.cs for why a plain "one fixed seed for the whole test" isn't enough on
    // its own (a few tests retry `new World()` expecting each attempt to roll differently).
    // DebugResetSeedSequence() re-zeroes the per-thread call counter each iteration so a given test
    // always sees the exact same sequence of seeds regardless of which OTHER test last ran on
    // whichever pooled thread ends up running it this time.
    //
    // Only the CONSOLE OUTPUT stays ordered the old way: each slot in `results` is written by
    // exactly one Task, then printed back in the original `Tests` order afterward, so anyone
    // grepping/diffing the output sees the same order as the old single-threaded run, just arrives
    // many times faster.
    public static int Run()
    {
        var results = new (bool Ok, string? ExceptionText)[Tests.Length];
        Parallel.For(0, Tests.Length, i =>
        {
            World.DebugDeterministicSeedBase = i;
            World.DebugDeterministicSeedBase = i;
            World.DebugResetSeedSequence();
            try { results[i] = (Tests[i].Run(), null); }
            catch (Exception ex) { results[i] = (false, ex.ToString()); }
            finally { World.DebugDeterministicSeedBase = null; }
        });

        int failed = 0;
        for (var i = 0; i < Tests.Length; i++)
        {
            var name = Tests[i].Name;
            var (ok, exceptionText) = results[i];
            if (exceptionText is not null)
                Console.WriteLine($"  {name}: EXCEPTION {exceptionText}");

            Console.WriteLine(ok ? $"OK   {name}" : $"FAIL {name}");
            if (!ok) failed++;
        }

        Console.WriteLine($"\n{Tests.Length - failed}/{Tests.Length} passed");
        return failed == 0 ? 0 : 1;
    }
}
